CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(120) NOT NULL,
    username VARCHAR(60) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL,
    base_role VARCHAR(30) NOT NULL,
    can_register_production BOOLEAN NOT NULL,
    can_register_dispatch BOOLEAN NOT NULL,
    can_register_consumption BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_users_username UNIQUE (username)
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(120) NOT NULL,
    type VARCHAR(80),
    unit_of_measure VARCHAR(30) NOT NULL,
    current_stock INT NOT NULL,
    minimum_stock INT,
    active BOOLEAN NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE supplies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(120) NOT NULL,
    category VARCHAR(80),
    unit_of_measure VARCHAR(30) NOT NULL,
    current_stock INT NOT NULL,
    minimum_stock INT,
    active BOOLEAN NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE stock_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    movement_type VARCHAR(30) NOT NULL,
    entity_type VARCHAR(30) NOT NULL,
    product_id BIGINT,
    supply_id BIGINT,
    quantity INT NOT NULL,
    unit_of_measure VARCHAR(30) NOT NULL,
    previous_stock INT NOT NULL,
    new_stock INT NOT NULL,
    observation VARCHAR(500),
    registered_by_user_id BIGINT NOT NULL,
    movement_date DATE NOT NULL,
    registered_at TIMESTAMP(6) NOT NULL,
    status VARCHAR(30) NOT NULL,
    origin VARCHAR(30) NOT NULL,
    rejected_quantity INT,
    shift VARCHAR(50),
    client_or_destination VARCHAR(160),
    transport VARCHAR(80),
    guide_number VARCHAR(60),
    process_area VARCHAR(80),
    PRIMARY KEY (id),
    CONSTRAINT fk_stock_movements_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_stock_movements_supply FOREIGN KEY (supply_id) REFERENCES supplies (id),
    CONSTRAINT fk_stock_movements_user FOREIGN KEY (registered_by_user_id) REFERENCES users (id)
);

CREATE INDEX idx_stock_movements_date ON stock_movements (movement_date);
CREATE INDEX idx_stock_movements_user ON stock_movements (registered_by_user_id);

CREATE TABLE daily_closings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    closing_date DATE NOT NULL,
    closed_by_user_id BIGINT NOT NULL,
    total_production INT NOT NULL,
    total_dispatch INT NOT NULL,
    total_consumption INT NOT NULL,
    observation VARCHAR(500),
    closed_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_daily_closings_date UNIQUE (closing_date),
    CONSTRAINT fk_daily_closings_user FOREIGN KEY (closed_by_user_id) REFERENCES users (id)
);

CREATE TABLE alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    type VARCHAR(50) NOT NULL,
    message VARCHAR(300) NOT NULL,
    level VARCHAR(30) NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    resolved_at TIMESTAMP(6),
    resolved_by_user_id BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT fk_alerts_resolved_by FOREIGN KEY (resolved_by_user_id) REFERENCES users (id)
);

CREATE TABLE office_inventory_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(120) NOT NULL,
    category VARCHAR(80),
    unit_of_measure VARCHAR(30) NOT NULL,
    current_stock INT NOT NULL,
    minimum_stock INT,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE office_inventory_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    movement_type VARCHAR(30) NOT NULL,
    item_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    previous_stock INT NOT NULL,
    new_stock INT NOT NULL,
    observation VARCHAR(500),
    registered_by_user_id BIGINT NOT NULL,
    movement_date DATE NOT NULL,
    registered_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_office_inventory_movements_item FOREIGN KEY (item_id) REFERENCES office_inventory_items (id),
    CONSTRAINT fk_office_inventory_movements_user FOREIGN KEY (registered_by_user_id) REFERENCES users (id)
);

CREATE INDEX idx_office_inventory_movements_date ON office_inventory_movements (movement_date);
