CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT,
    username VARCHAR(60),
    module VARCHAR(80) NOT NULL,
    action VARCHAR(80) NOT NULL,
    entity VARCHAR(80),
    entity_id BIGINT,
    occurred_at TIMESTAMP(6) NOT NULL,
    ip VARCHAR(80),
    user_agent VARCHAR(300),
    correlation_id VARCHAR(80),
    previous_detail TEXT,
    new_detail TEXT,
    reason VARCHAR(500),
    PRIMARY KEY (id)
);

CREATE INDEX idx_audit_logs_occurred_at ON audit_logs (occurred_at);
CREATE INDEX idx_audit_logs_user ON audit_logs (user_id);
CREATE INDEX idx_audit_logs_correlation ON audit_logs (correlation_id);
