CREATE TABLE idempotency_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    idempotency_key VARCHAR(120) NOT NULL,
    endpoint VARCHAR(200) NOT NULL,
    user_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    result_type VARCHAR(80) NOT NULL,
    result_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_idempotency_user_endpoint_key UNIQUE (user_id, endpoint, idempotency_key)
);
