CREATE TABLE daily_alert_dismissals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    alert_date DATE NOT NULL,
    alert_type VARCHAR(50) NOT NULL,
    dismissed_by_user_id BIGINT NOT NULL,
    dismissed_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_daily_alert_dismissals_date_type UNIQUE (alert_date, alert_type),
    CONSTRAINT fk_daily_alert_dismissals_user FOREIGN KEY (dismissed_by_user_id) REFERENCES users (id)
);

CREATE INDEX idx_daily_alert_dismissals_date ON daily_alert_dismissals (alert_date);
