package com.indherco.postes.shared.enums;

public enum AlertType {
    STOCK_BAJO_PRODUCTO,
    STOCK_BAJO_INSUMO,
    DESPACHO_SIN_STOCK,
    CONSUMO_SIN_STOCK,
    DIA_SIN_CIERRE,
    REGISTRO_PRODUCCION_PENDIENTE,
    REGISTRO_DESPACHO_PENDIENTE,
    REGISTRO_CONSUMO_PENDIENTE
}
